app:
  name: "cool-password-manager"
  version: "1.0.0"
  issuer: "cool-password-manager"
  template_path: "/internal/app/templates/**/*.html"
  two_factor_duration: 20
  default_page: 1
  default_page_size: 10

http:
  port: "8080"
  host: "localhost"

logger:
  log_level: "debug"

db:
  pool_max: 2